//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tijdWebserviceClient.TijdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TijdService.ITijdService")]
    public interface ITijdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITijdService/GetServerTime", ReplyAction="http://tempuri.org/ITijdService/GetServerTimeResponse")]
        System.DateTime GetServerTime();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITijdServiceChannel : tijdWebserviceClient.TijdService.ITijdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TijdServiceClient : System.ServiceModel.ClientBase<tijdWebserviceClient.TijdService.ITijdService>, tijdWebserviceClient.TijdService.ITijdService {
        
        public TijdServiceClient() {
        }
        
        public TijdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TijdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TijdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TijdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
    }
}
